### ISSUE TITLE
Please release new version with newer net.bytebuddy:byte-buddy for Java 10

### ISSUE THREAD

**Issue by Necropaw** [curioswitch/curiostack#124]
### Expected behavior
Runs with Java 10

### Current behavior
Because of using [net.bytebuddy:1.7.0 in protobuf-jackson:0.11](https://mvnrepository.com/artifact/org.curioswitch.curiostack/protobuf-jackson/0.1.1) the upstream error happens: https://github.com/raphw/byte-buddy/issues/351

**Comment by chokoswitch** [comment]
Thanks for the note - released 0.2.0 with latest byte-buddy
