### ISSUE TITLE
Make unbounded/unlimited Armeria settings configurable?

### ISSUE THREAD

**Issue by demongaorui** [curioswitch/curiostack#144]
Based on the discussion in Armeria slack channel: https://line-armeria.slack.com/archives/C1NGPBUH2/p1527204753000180

I'd like to make some unbounded/unlimited Armeria settings configurable in curiostack ServerModule. For example, `serverBuilder.maxNumConnections()`, `serverBuilder.defaultRequestTimeoutMillis()`
and `serverBuilder.defaultMaxRequestLength()`.

Encounted some server issues recently. One of our grpc api services running multiple times rest client calls, the service submit all these blocking calls into a fixed thread pool executor. While when this service becomes slow then all the threads of the fixed thread pool will be captured and the server will be unuseble, but the `/internal/health` api could still response `ok`(sometimes very slowly). This cause k8s think the server is alive even if the server is unuseble already. Guess adding some unbounded/unlimited Armeria settings maybe helpful to prevent the thread pool ran out of threads for a certain slow api. This at least help the server to serve other api requests even if one certain api becomes very slow.

Excutor:
```
    @Provides
    @Singleton
    static ListeningExecutorService executor() {
      return MoreExecutors.listeningDecorator(
          Executors.newFixedThreadPool(
              20, new ThreadFactoryBuilder().setNameFormat("blockingExcutor-%d").setDaemon(true).build()));
    }

```

Service:
```
 public void someService(
      SomeServiceRequest request, StreamObserver<SomeServiceResponse> responseObserver) {
    FuturesExtra.addCallback(
        executor.submit(
            () -> {
              int somevalue1 =
                  CompletableFuturesExtra.toListenableFuture(
                      someHttpClient.execute(HttpHeaders.of(HttpMethod.GET, "/somePath"))
                          .aggregate()
                          .thenApply(
                              aggregated -> {
                                int someVal = 10;
                                return someVal;
                              })
                          .exceptionally(
                              e -> {
                                throw new RuntimeException(e);
                              })).get();

              int somevalue2 =
                  CompletableFuturesExtra.toListenableFuture(
                      someHttpClient.execute(HttpHeaders.of(HttpMethod.GET, "/somePath"))
                          .aggregate()
                          .thenApply(
                              aggregated -> {
                                int someVal = 10;
                                return someVal;
                              })
                          .exceptionally(
                              e -> {
                                throw new RuntimeException(e);
                              })).get();
              return SomeServiceResponse.newBuilder()
                  .setSomething(somevalue1)
                  .setSomething2(somevalue2)
                  .build();
            }),
        response -> {
          responseObserver.onNext(response);
          responseObserver.onCompleted();
        },
        t -> {
          logger.error("Unexpected error.", t);
          responseObserver.onError(t);
        });
  }
```

**Comment by demongaorui** [comment]
@chokoswitch 

If the idea of `making unbounded/unlimited Armeria settings configurable in curiostack ServerModule.` make sense to you. I would like to do the implementation :)

**Comment by chokoswitch** [comment]
Arbitrary customization of the `ServerBuilder` is already possible by `@Provides`'ing `Consumer<ServerBuilder>>`.

https://github.com/curioswitch/curiostack/blob/master/common/server/framework/src/main/java/org/curioswitch/common/server/framework/ServerModule.java#L195

Does that not work?

**Comment by demongaorui** [comment]
Yes, serverCustomizers will work. While adding some conservative default values and make them easier to config in https://github.com/curioswitch/curiostack/blob/master/common/server/framework/src/main/resources/reference.conf#L56 will be more handy?

**Comment by chokoswitch** [comment]
Most of those settings are already configurable using armeria flags
(tweakable with command line system properties). We shouldn't duplicate
flags here too or it's confusing with little extra value.

https://line.github.io/armeria/apidocs/com/linecorp/armeria/common/Flags.html

Adding max connections to that Flags in armeria seems like a good idea
though.

**Comment by demongaorui** [comment]
Make sense, gonna to raise a discussion about add max connections flag in armeria issues.


Btw, for the above example service, I tried that if not using an executor to run blocking HTTP calls in blockingExcutor thread, then the blocking calls with block armeria-common-worker-nio-*-* thread. And about 20% possibility, the request will be idle and never get a response. Is this caused by something like amaeria event loop mechanism kill blocked worker nio thread with some timeout or other rules?

**Comment by chokoswitch** [comment]
I'm not aware of any timeout mechanism of the worker threads - it might be interesting looking at threaddumps during that time to see if the thread is deadlocked for some reason. Also would definitely be good to switch to using an asynchronous client for those problematic calls (armeria-retrofit is asynchronous).

Anyways, will close this issue out since we'd rather use the armeria flags for this sort of tweaking, feel free to file more issues with other suggestions!

**Comment by chokoswitch** [comment]
Also just thought of it, but if you do a blocking get of the result from an
armeria http client, indeed there would be good chance of deadlock. The
http client will be assigned a random event loop thread but that thread may
be the one blocked on the server side - Netty/armeria thread scheduling
expects the event loop to never be blocked so also assumes it doesn't block
on itself.

**Comment by demongaorui** [comment]
Just noticed your comment https://github.com/curioswitch/curiostack/issues/144#issuecomment-392730721  Sounds like a good matching of the situation encountered before. Gonna try to find a way to reproduce the deadlock.
