### ISSUE TITLE
Migrate to Circleci 2.0?

### ISSUE THREAD

**Issue by demongaorui** [curioswitch/curiostack#164]
https://circleci.com/blog/sunsetting-1-0/
> August 31, 2018 is the Final Day for 1.0 Builds

Any plan to migrate the CI of curiostack to Circleci 2.0?

**Comment by chokoswitch** [comment]
Actually PR building was migrated to Cloudbuild a while ago and that hasn't been used. Removed the confusing `circle.yml`

**Comment by demongaorui** [comment]
Oh~~  OK
