### ISSUE TITLE
how to set json PropertyNamingStrategy SNAKE_CASE？

### ISSUE THREAD

**Issue by RyouZhang** [curioswitch/curiostack#301]
how to set json PropertyNamingStrategy SNAKE_CASE？

**Comment by chokoswitch** [comment]
I think you're referring to preserving the case of the fields in the proto file. You can do that by setting this option when constructing a `MessageMarshaller`.

https://github.com/curioswitch/curiostack/blob/master/common/grpc/protobuf-jackson/src/main/java/org/curioswitch/common/protobuf/json/MessageMarshaller.java#L301

Is this what you're looking for?

**Comment by RyouZhang** [comment]
I want  golang and java have same json output。
for example:
generate go code has json tag ”json: first_name“
but java is “firstName”

**Comment by chokoswitch** [comment]
In that case, that option should be what you're looking for. In Java, the default is to use camelcase in the upstream JSON serializer as documented here, but maybe Go has the opposite defaults.

https://github.com/protocolbuffers/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L250

**Comment by RyouZhang** [comment]
thanks，reflect to set PropertyNamingStrategy SNAKE_CASE is not useful. The keypoint is proto gen code. Please close the issue.
