### ISSUE TITLE
java-cloud-builder: npm install fails

### ISSUE THREAD

**Issue by gavinreaney** [curioswitch/curiostack#304]
When running a build inside the java-cloud-builder container, npm install is failing.

Repro steps:
1) Clone the repo at https://github.com/infostellarinc/stellarstation-api
2) Mount the source code into the container: docker run -it --rm -v `pwd`:/root/stellarstation-api curiostack/java-cloud-builder /bin/bash
3) cd /root/stellarstation-api
4) ./gradlew :stubs:nodejs:installProtocPlugins

This fails with:
> grpc@1.20.3 install /root/stellarstation-api/stubs/nodejs/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

sh: 1: node-pre-gyp: Permission denied

Digging a bit deeper we can directly try to run the command:

/root/.gradle/curiostack/node/11.13.0/node-v11.13.0-linux-x64/bin/node /root/.gradle/curiostack/node/11.13.0/node-v11.13.0-linux-x64/bin/npm install --no-save grpc-tools@1.6.6

This fails in the same way. I found that adding --unsafe-perm makes it get past this error. Alternatively, running the container as a non-root user might work too.

After doing that I got another error:
/usr/bin/env: ‘node’: No such file or directory

I was able to fix this by adding: --scripts-prepend-node-path to the command.

**Comment by chokoswitch** [comment]
Thanks for the report! After migrating to nodejs 11, some libraries that used to have prebuilt binaries now don't, and it seems to be the trend for packages to be moving away from offering prebuilt binaries in favor of webassembly bindings. Unfortunately, `node-pre-gyp` is very finicky and the world is full of issues getting it to run...

I notice that `grpc-js` is in beta now. Would you consider giving it a try? They'll be easier for users to use because chrome debugging works properly for a pure-js library, and it can be very tricky getting the C++-based library to even load in things like Electron so they aren't so useful in my experience.

**Comment by gavinreaney** [comment]
I haven't tried grpc-js yet, but I can report that when I ran the build as a non-root user I didn't see any issues.

**Comment by chokoswitch** [comment]
Interesting - how did you run the build as a non-root user? I can't find any parameter in Cloud Build to change the user. I played with adding a `USER` to the `Dockerfile` but it can't actually access anything in `/workspace` which is mounted as root. If it's simple to run as non-root, I think we should update `java-cloud-builder` to not be root anymore.

**Comment by gavinreaney** [comment]
So far I didn't try this directly with cloud build. I basically ran the docker container on my machine, with my source dir mounted in the container. With the container running, I added the users so they match the permissions of the mounted directory, and then ran the build.

To make it work in cloud build, I was going to try hacking the command line that is specified in the cloud build config to do a bunch of stuff as root (creating users, copying directories around, etc) before running gradle under the newly created user.

**Comment by gavinreaney** [comment]
I just used --unsafe-perm in our install command for now.

**Comment by chokoswitch** [comment]
Thanks - I think that should always be safe inside a docker build so it seems like a good workaround (`npm` seems to be more strict than `yarn` about trying to save your computer from a meltdown...). So will go ahead and mark this one closed, I think it's an issue more with `npm` than `curiostack`.
