### ISSUE TITLE
java-cloud-builder: bzip2 disappeared but is needed for some build steps

### ISSUE THREAD

**Issue by gavinreaney** [curioswitch/curiostack#318]
Not sure why, but bzip2 is no longer in the java-cloud-builder image. It was there late last week.

I guess there is some change in the base images.

**Comment by chokoswitch** [comment]
Hmm - yeah it must be a change in the OpenJDK image.

Just for reference what build step do you see is using bzip2? The cloudbuild steps themselves should be using lz4.

**Comment by gavinreaney** [comment]
Ah to clarify it's something in our gradle build that indirectly uses it. Downloading and unzipping phantomjs something or other.

**Comment by gavinreaney** [comment]
Do you have a rough idea of when you could update the java-cloud-builder dockerfile to include any removed tools? Just checking whether I should wait a bit or fix our build another way :)

**Comment by chokoswitch** [comment]
I merged a change to install `bzip2` into the cloud builder image. The new image will be built and pushed by docker hub, it usually takes at least 1/2 hour for that to happen though.

In the meantime, you may want to confirm you're actually using that phantomjs (presumably for screenshot testing) ;)
