### ISSUE TITLE
java-cloud-builder: access to https servers fails because of missing CA certificates

### ISSUE THREAD

**Issue by kenichi-fukushima** [curioswitch/curiostack#322]
Build of our project (infostellar/starcoder) is failing because of https errors.
https://circleci.com/gh/infostellarinc/starcoder/626?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
go: golang.org/x/sys@v0.0.0-20180906133057-8cf3aee42992: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: x509: certificate signed by unknown authority)
```

After installing the "ca-certificates" apt package, the error was gone.

I'm not very sure but perhaps there was a change to an image up in the inheritance chain.

**Comment by chokoswitch** [comment]
Thanks for reporting - we found in #319 that it seems openjdk base image has slimmed down (probably too much...). Please let me know if you find any more missing tools, or also feel free to send a PR updating the `Dockerfile` like in the attached issue. Thanks!
