### ISSUE TITLE
ProtobufRedisLoadingCache deleteFromRedis should return a value

### ISSUE THREAD

**Issue by gavinreaney** [curioswitch/curiostack#378]
There are some use cases where it is useful to know whether the key being deleted actually existed or not. Could ProtobufRedisLoadingCache.deleteFromRedis return a value?

I suppose some people might also want to know that the operation completed or not rather than it being fire and forget.

**Comment by chokoswitch** [comment]
Sounds good - doesn't seem to be any good reason for the current API that doesn't return anything.
