### ISSUE TITLE
gradle/get-jdk.sh - JAVA_HOME and downloaded JDK tar

### ISSUE THREAD

**Issue by rtubio** [curioswitch/curiostack#406]
The hotspot JDK package for MAC does not include a valid JDK at the root of the package. Instead, the JDK directory is contained under "Contents/Home". Therefore

    export JAVA_HOME="$OPENJDK_DIR/jdk-12.0.1+12"

... needs to be changed to:

    export JAVA_HOME="$OPENJDK_DIR/jdk-12.0.1+12/Contents/Home"

Otherwise, gradle stops working since the JDK binary files are not detected under the set JAVA_HOME directory.

**Comment by chokoswitch** [comment]
This and #405 have been fixed in the latest version of CurioStack and now we have a continuous build running on a Mac, so hopefully these issues don't show up again in the future. Thanks again for reporting!
