### ISSUE TITLE
Slack Workspace invite link has expired

### ISSUE THREAD

**Issue by danada** [curioswitch/curiostack#481]
The slack workspace invitation link has expired meaning newcomers are not able to join the workspace unless explicitly invited by someone who has already joined.

https://github.com/curioswitch/curiostack#have-a-question

Links should be good for up to 2000 people, not sure why this one expired.

**Comment by chokoswitch** [comment]
Thanks for reporting! One hypothesis is it only tracks visits, not signups, and crawlers use it up https://github.com/line/armeria/pull/2265

Will update the link

**Comment by chokoswitch** [comment]
Nevermind on hypothesis, Github seems to add nofollow automatically ;)
