### ISSUE TITLE
org.curioswitch.gradle-curio-cloudbuild-github-plugin Information

### ISSUE THREAD

**Issue by stewartbryson** [curioswitch/curiostack#501]
Sorry for the informational issue... but I was just trying to understand what this plugin does. Any docs, sample repos, etc.?

Thank you.

**Comment by chokoswitch** [comment]
Thanks for the question and sorry for the general lack of docs! That gradle plugin is just a simple executor of [this](https://github.com/curioswitch/curiostack/tree/master/tools/cloudbuild-github) NodeJS binary which sets up GCP cloud functions to run cloudbuild for PRs. It sets up a webhook for GitHub and a Pub/Sub listener to monitor the build and update the PR status with it. 

That being said, the plugin is deprecated now. This cloud function was made before any official GitHub integration in Cloud Build itself. Even when the first integration came out in the form of GitHub triggers, that didn't support fork PRs so we have continued to use this cloud function. Now, GitHub app triggers for Cloud Build support fork PRs and there is no need to use a user function anymore. If you haven't tried out the new GitHub app triggers, I recommend giving them a look :) https://cloud.google.com/cloud-build/docs/create-github-app-triggers

**Comment by chokoswitch** [comment]
Let me go ahead and close this issue. Please feel free to reopen or file another one if you have more questions @stewartbryson
