### ISSUE TITLE
Migrating to Github Cloud Build App (.git folder not found)

### ISSUE THREAD

**Issue by davidk81** [curioswitch/curiostack#513]
This question relates to [curiostack/tools/cloudbuild-github](https://github.com/curioswitch/curiostack/tree/master/tools/cloudbuild-github), we currently use it to trigger CI on **pull requests**.

We have encountered an issue where the `.git` folder is missing on remote CI builds after migrating to the [Github Cloudbuild App](https://github.com/marketplace/google-cloud-build). This issue is documented [here on the github cloud-builder plugijn](https://github.com/GoogleCloudPlatform/cloud-builders/issues/236) with a rather ugly workaround.

Just wondering if anyone here has migrated away from the curiobuild-github tool and have a better approach to the problem of missing `.git` folder? thanks!

**Comment by chokoswitch** [comment]
Thanks for filing this issue! Indeed with the advent of the official Cloud Build App, our webhook is effectively deprecated.

Curiostack has migrated and uses the ugly, but as long as it works guess it's ok, workaround...

https://github.com/curioswitch/curiostack/blob/master/cloudbuild-pr.yaml#L13

**Comment by chokoswitch** [comment]
Looking at that config again, I think askpass isn't set up correctly - it works since curiostack is open source but would need to add these two lines that generate the askpass script for a closed source one

https://github.com/curioswitch/curiostack/blob/master/tools/cloudbuild-github-functions/config.yml#L19

**Comment by davidk81** [comment]
Thanks so much for the prompt and the helpful response! we've decided take a similar approach with difference being we're trying out Github authentication with a SSH deploy key instead of ASKPASS. This will definitely be a good reference for us.
