### ISSUE TITLE
ProtobufRedisLoadingCache sometimes will timeout

### ISSUE THREAD

**Issue by davidk81** [curioswitch/curiostack#562]
When invoking `ProtobufRedisLoadingCache.getIfPresent(k).get(15, TimeUnit.SECONDS)` inside the request context `eventloop`, sometimes invocation will timeout (but it is not consistent).

I'm suspecting the reason is 
[CurrentRequestContextExecutor](https://github.com/curioswitch/curiostack/blob/601d52d08e7c9221c74d1bde1b1ed85f7b8e0093/common/server/framework/src/main/java/org/curioswitch/common/server/framework/armeria/CurrentRequestContextExecutor.java#L40) will attempt to detect and use the `eventloop` associated with the request context, however, it is unclear to me why it happens inconsistently and only occasionally.

we have since attempted to 'break' this detection by wrapping the call in a separate thread, but this did not solve the problem. eg:
```
var future = streamingStateCache.getIfPresent(key);
executor.submit(
  () -> {
       streamingState =
            future.get(CACHE_FETCH_TIMEOUT_SECONDS, TimeUnit.SECONDS);
  })
  .get(); // blocks eventloop
```

I have now realize perhaps I should put the `getIfPresent` call inside the separate thread. eg:
```
executor.submit(
  () -> {
       var future = streamingStateCache.getIfPresent(key);
       streamingState =
            future.get(CACHE_FETCH_TIMEOUT_SECONDS, TimeUnit.SECONDS);
  })
  .get(); // blocks eventloop
```

**does this seem like it will 'break' the event loop detection by `CurrentRequestContextExecutor`?**
also, i'm not sure if i have diagnosed this problem correctly, open to any suggesions!

I realize it is a terrible idea to block on the `eventloop`, i have already tried to make this method return a future instead of blocking, but a lot of existing downstream logic depends on the result of the `cache.get`, so unit tests needs to be re-worked. this approach is still being worked on in a separate branch.

thanks in advance for any feedback!

tagging @danada

**Comment by chokoswitch** [comment]
Hey - sorry for the slow response! Yeah it's not allowed to block the event loop. I don't think either of those options can work because you still call a blocking `.get` on the event loop. This has a chance of still working as long as the client call is made from a different event loop but this is random and you are seeing sporadic behavior for when the client call reuses the same event loop and deadlocks.

There really isn't any way to fix this other than

1) Use asynchronous pattern throughout
2) Go to your top level API method (a gRPC handler?) and wrap your logic in a submission to the `RequestContext.blockingTaskExecutor` to get off the event loop.

**Comment by davidk81** [comment]
thanks for the response!
i've actually tested my hypothesis and you were right that both does not produce reliable results. 

i did some localhost testing for your #1 suggestion, and it seem the cache never timed out. the problem is i had to disable a significant amount of unit testing.

your #2 suggestion is something i did not think of, i will look into how i can achieve that.

thanks again, much appreciated!

**Comment by chokoswitch** [comment]
Cool - #2 is of course not ideal since switching between threads adds some overhead, so hopefully you can get to #1 at least at some point!
