### ISSUE TITLE
Certificates for https://developers.curioswitch.org/ have been expired

### ISSUE THREAD

**Issue by ikhoon** [curioswitch/curiostack#643]
I got an `SSLHandshakeException` while downloading Javadoc form https://developers.curioswitch.org/apidocs/java/element-list
```
Download https://developers.curioswitch.org/apidocs/java/element-list
Download failed: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
```
After checking the website, I saw that the certificates for https://developers.curioswitch.org/ expired at 2024/3/10 (3 days ago).
<img width="487" alt="image" src="https://github.com/curioswitch/curiostack/assets/1866157/9645f779-1091-4048-99ca-2a4434ea684b">

**Comment by chokoswitch** [comment]
Thanks for the report! It seems Firebase deprecated their previous way of setting DNS without any notification... I have tried updating DNS and let's see if it resolves after propagating

**Comment by chokoswitch** [comment]
Hi @ikhoon - it looks like the site is back up, let me know if you still see any issue

**Comment by ikhoon** [comment]
It works very well. Thanks for the quick response. ❤️
