### ISSUE TITLE
Remove dependency of common server framework in auth server?

### ISSUE THREAD

**Issue by demongaorui** [curioswitch/curiostack#65]
Is it possible to replace ` compile project(':common:server:framework')` in 
https://github.com/curioswitch/curiostack/blob/f37d3d71985abd5b13f76cae4edf495ed12516d1/auth/server/build.gradle#L32
 by `compile group: 'org.curioswitch.curiostack', name: 'curio-server-framework', version: '0.0.1'` in
https://mvnrepository.com/artifact/org.curioswitch.curiostack/curio-server-framework ?

If it's possible, then it will be very convenient to dev multiple servers in separate git repositories for making server side of an organization according to multiple micro-services by following minium gradle build files:

1. Root gradle.build
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.curioswitch.curiostack:gradle-curiostack-plugin:0.0.17'
    }
}

apply plugin: 'org.curioswitch.gradle-curiostack-plugin'

allprojects {
    project.group = 'org.curioswitch.curiostack'
}

gcloud {
    clusterBaseName = 'curioswitch'
    cloudRegion = 'asia-northeast1'
    clusterKubernetesVersion = '1.6.1'
}
```

2. Server module gradle.build
```
apply plugin: 'org.curioswitch.gradle-curio-server-plugin'

archivesBaseName = 'curio-auth-server'
mainClassName = 'org.curioswitch.auth.server.Main'

dependencies {
    compile project(':auth:api')
    compile 'org.curioswitch.curiostack:curio-server-framework: 0.0.1'`

    apt 'com.google.dagger:dagger-compiler'
    compile 'com.google.dagger:dagger'
}
```

Don't need to directoly copy any modules from curiostack repository(which makes it difficult to keep server framework module up to date) anymore.

**Comment by demongaorui** [comment]
Tried to replace `compile project(':common:server:framework')` to
`  compile 'org.curioswitch.curiostack:curio-server-framework:0.0.1' `
and get error when try to run auth server like:
```
error: cannot access HttpRequest
  class file for com.linecorp.armeria.common.http.HttpRequest not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.linecorp.armeria.common.http.HttpRequest not found
1 error
:auth:server:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':auth:server:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
8 actionable tasks: 1 executed, 7 up-to-date
Compilation failed; see the compiler error output for details.
16:38:40: External task execution finished 'run'.
```

Is this because `org.curioswitch.curiostack:curio-server-framework:0.0.1'` is out of date?

**Comment by chokoswitch** [comment]
`curio-server-framework` hasn't been synced to maven central in a long time, in general `jcenter` is the canonical source for it during alpha phases. The current version is `0.0.56`. Though it is not intended for users to specify the version of `curio-server-framework`, only the `gradle-curiostack-plugin` should be applied on the root project and it manages all dependencies. `gradle-curiostack-plugin` is currently `0.0.114`. No need to copy anything around.

It's indeed true that the servers in this repository serve as a bad example since they use project dependencies, at some point I will move `eggworld` out to be a clearer example of usage from a user's perspective.

**Comment by demongaorui** [comment]
Thanks for your info. Made a server successfully by doing:
```
-    compile project(':common:server:framework')
+    compile 'org.curioswitch.curiostack:curio-server-framework'
```
with latest `0.0.114` version of `gradle-curiostack-plugin` and the related server plugin!

For moving `eggworld` out, I would like to help. Could you share where(which repository or which dir inside this repository) you want to move it to so that I could try to do that, and add more documents in the same time as well 😉
